param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectRoot
)

$ErrorActionPreference = 'Stop'

function Get-ModulePurpose($name) {
    switch -Regex ($name) {
        '^00Rule$' { '项目架构、项目规则、自研框架规则、Lua/C# 交互规则、全项目通用但与常规不同的操作方式。'; break }
        '^01ProjectOverview$' { '项目总览、游戏规则、玩法、大体功能、主干脚本路径、快速检索说明。'; break }
        '^02LevelEditor$' { '关卡编辑器相关方案、工具说明、编辑器实现、调整日志。'; break }
        '^03LevelLoading$' { '游戏关卡加载链路、地图加载、颜色方块加载、预览图加载、加载优化。'; break }
        '^04PlayerInput$' { '用户输入系统、拖拽填充、交互流程、输入相关修复记录。'; break }
        '^05PropSystem$' { '道具系统、道具解锁、消除错误道具、回退道具、道具弹窗。'; break }
        '^06Review$' { '项目开发功能审查、实现审查、审查清单、风险对照。'; break }
        '^07ADMD$' { '广告接入、埋点接入、数据统计、广告/埋点相关规则和实现记录。'; break }
        '^08OUFDevelopmentLogs$' { '连接 Orange Unity Forge 保存在 docs/forge-artifacts 下的功能开发日志、Context Brief、SDD、Plan、Report、Evidence，只保存索引不复制正文。'; break }
        default { '项目扩展模块。' }
    }
}

function Get-ModuleIndexName($name) {
    if ($name -match '^(\d{2})') {
        return "$($Matches[1])00Index.md"
    }
    return 'Index.md'
}

if (-not (Test-Path -LiteralPath $ProjectRoot -PathType Container)) {
    throw "Project root not found: $ProjectRoot"
}

$CatalogRoot = Join-Path (Get-Item -LiteralPath $ProjectRoot).FullName '.ACSDM'
if (-not (Test-Path -LiteralPath $CatalogRoot -PathType Container)) {
    throw "ACSDM catalog root not found: $CatalogRoot"
}

$rootLines = @()
$rootLines += '# 0000 ACSDM Root Index'
$rootLines += ''
$rootLines += '## 命名规范'
$rootLines += ''
$rootLines += '使用 `<模块编号><文档编号><文档主题>.md`。`xx00Index.md` 为模块索引。'
$rootLines += ''
$rootLines += '## 检索方法'
$rootLines += ''
$rootLines += '先读根索引，再读模块索引，最后只读取与任务直接相关的 md 文档。'
$rootLines += ''
$rootLines += '## 模块总览'
$rootLines += ''
$rootLines += '| 模块 | 用途 | 索引文件 | 关键词 | 文档数量 | 更新时间 |'
$rootLines += '|---|---|---|---|---:|---|'

foreach ($dir in Get-ChildItem -LiteralPath $CatalogRoot -Directory -Force | Sort-Object Name) {
    $indexName = Get-ModuleIndexName $dir.Name
    $purpose = Get-ModulePurpose $dir.Name
    $mdFiles = @(Get-ChildItem -LiteralPath $dir.FullName -File -Filter '*.md' -Force | Sort-Object Name)
    $rootLines += "| ``$($dir.Name)`` | $purpose | ``$indexName`` |  | $($mdFiles.Count) | $($dir.LastWriteTime.ToString('s')) |"

    $indexPath = Join-Path $dir.FullName $indexName
    $moduleLines = @()
    $moduleLines += "# $($indexName -replace '\.md$','') $($dir.Name)"
    $moduleLines += ''
    $moduleLines += '## 命名规范'
    $moduleLines += ''
    $moduleLines += '本目录使用 `<模块编号><文档编号><文档主题>.md` 命名。`xx00Index.md` 为本目录索引。'
    $moduleLines += ''
    $moduleLines += '## 检索方法'
    $moduleLines += ''
    $moduleLines += '1. 先通过关键词定位模块。'
    $moduleLines += '2. 读取本索引的用途、脚本、方法、行号字段。'
    $moduleLines += '3. 只打开与当前需求直接相关的 md 文档。'
    $moduleLines += '4. 不进行全目录正文读取。'
    $moduleLines += ''
    $moduleLines += '## 模块用途'
    $moduleLines += ''
    $moduleLines += $purpose
    $moduleLines += ''
    $moduleLines += '## 文档索引'
    $moduleLines += ''
    $moduleLines += '| md 文件名 | 加入时间 | 最新修改时间 | 用途 | 涉及脚本名称 | 脚本简要功能说明 | 涉及方法名称 | 涉及行数 | 检索关键词 | 记录类型 |'
    $moduleLines += '|---|---|---|---|---|---|---|---|---|---|'
    foreach ($file in $mdFiles) {
        if ($file.Name -eq $indexName) { continue }
        $time = $file.LastWriteTime.ToString('s')
        $moduleLines += "| `$($file.Name)` | $time | $time | 待补充 |  |  |  |  |  | 待分类 |"
    }
    Set-Content -Path $indexPath -Value $moduleLines -Encoding UTF8
}

$rootLines += ''
$rootLines += '## 模块映射兼容表'
$rootLines += ''
$rootLines += '| 当前目录 | 标准目录 | 说明 |'
$rootLines += '|---|---|---|'
$rootLines += ''
$rootLines += '## 最近更新'
$rootLines += ''
$rootLines += "- $(Get-Date -Format s): regenerated by acsdm-update-index.ps1"

Set-Content -Path (Join-Path $CatalogRoot '0000ACSDMRootIndex.md') -Value $rootLines -Encoding UTF8
Write-Output "Updated ACSDM indexes under: $CatalogRoot"